### ISSUE TITLE
Failed to compile Linux QT wallet 

### ISSUE THREAD

**Issue by anemol** [l8nit3tr0ubl3/GirlsToken-2.0#4]
```

g++: error: /home/exp/wallets/GirlsToken-2.0/src/leveldb/libleveldb.a: No such file or directory
g++: error: /home/exp/wallets/GirlsToken-2.0/src/leveldb/libmemenv.a: No such file or directory
Makefile:320: recipe for target 'GirlsToken2.0.1' failed
make: *** [GirlsToken2.0.1] Error 1

```

**Comment by l8nit3tr0ubl3** [comment]
will look into it immediately, however i am currently on  vacation using a 3g connection, so may take me a short while for the fix. Thank you for reporting this to me 😊

**Comment by l8nit3tr0ubl3** [comment]
Ok, i have pushed a small fix, however am about 300 km away from my build machine. If you go to your GirlsToken-2.0 folder and do a "git pull" and then try building again all should work.
Please let me know 😊

**Comment by anemol** [comment]
Thanks. Better but still not ok

```
/usr/bin/ld : ne peut trouver -lboost_system-mgw49-mt-s-1_55
/usr/bin/ld : ne peut trouver -lboost_filesystem-mgw49-mt-s-1_55
/usr/bin/ld : ne peut trouver -lboost_program_options-mgw49-mt-s-1_55
/usr/bin/ld : ne peut trouver -lboost_thread-mgw49-mt-s-1_55
collect2: error: ld returned 1 exit status
make: *** [GirlsToken2.0.1] Erreur 1

```

I have the v1.58 of Boost and no problem to compile other wallets.

**Comment by l8nit3tr0ubl3** [comment]
Ok if you look at that error, it is trying to use boost 1.55, which is what i used to compile. If you go into the girlstoken-qt.pro file you will see the dependancies that i used. You need to change the numbers to match the versions you are using.

On Jul 27, 2017 5:31 AM, anemol <notifications@github.com> wrote:

Thanks. Better but still not ok

/usr/bin/ld : ne peut trouver -lboost_system-mgw49-mt-s-1_55
/usr/bin/ld : ne peut trouver -lboost_filesystem-mgw49-mt-s-1_55
/usr/bin/ld : ne peut trouver -lboost_program_options-mgw49-mt-s-1_55
/usr/bin/ld : ne peut trouver -lboost_thread-mgw49-mt-s-1_55
collect2: error: ld returned 1 exit status
make: *** [GirlsToken2.0.1] Erreur 1



I have the v1.58 of Boost and no problem to compile other wallets.

**Comment by anemol** [comment]
I deleted and git clone again

```
qmake Linux-qt.pro 
/media/SSD/Workspace/GirlsToken-2.0/Linux-qt.pro:141: Parse Error ('   �')
/media/SSD/Workspace/GirlsToken-2.0/Linux-qt.pro:141: Unterminated conditional block at end of file
Error processing project file: Linux-qt.pro
```

**Comment by l8nit3tr0ubl3** [comment]
Ok, so I have uploaded a pre-built linux binary on the "releases" page ->  
https://github.com/l8nit3tr0ubl3/GirlsToken-2.0/releases/download/2.0.1.0/GirlsToken2.0.1   
However if you would like to build your own please follow the steps below:  
1) ensure all dependencies are satisfied:  
`sudo apt-get install libdb5.1-dev libdb5.1++-dev libboost-all-dev libqrencode-dev qt4-qmake libqt4-dev build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev automake`  
2) enter 'src' and build daemon to ensure leveldb is built correctly:  
`cd src && make -f makefile.unix`  
3) move back to main directory and build qt wallet:
`cd ../ && qmake-qt4 linux-qt.pro && make`  

Hope this helps :)

**Comment by anemol** [comment]
Your fixes are good.
Deamon compilation  and Qt-wallet compilation are ok now.
Thanks :)

**Comment by l8nit3tr0ubl3** [comment]
Glad i could get it fixed for you 😊 sorry for the delay
